apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-api
  namespace: tech-challenge-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-api
  template:
    metadata:
      labels:
        app: game-api
    spec:
      containers:
      - name: game-api
        image: SEU_REGISTRY_ECR/tech-challenge-fiap-game:latest # Substitua pelo seu Registry ECR
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: game-api-config
        - secretRef:
            name: game-api-secrets
        
        # ---- INÍCIO: Configuração New Relic Adicionada ----
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secrets
              key: license-key
        - name: NEW_RELIC_APP_NAME
          value: "tech-challenge-game-api" # Ajustado para o nome do projeto atual
        - name: CORECLR_ENABLE_PROFILING
          value: "1"
        - name: CORECLR_PROFILER
          value: "{36032161-FFC0-4B61-B559-F6C5D41BAE5A}"
        - name: CORECLR_NEWRELIC_HOME
          value: "/usr/local/newrelic"
        - name: CORECLR_PROFILER_PATH
          value: "/usr/local/newrelic/libNewRelicProfiler.so"
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: NEW_RELIC_LOG_LEVEL
          value: "info"
        # ---- FIM: Configuração New Relic Adicionada ----

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30