apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: tech-challenge-game
  labels:
    app: postgres-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3  # AWS EBS storage class
  resources:
    requests:
      storage: 10Gi