apiVersion: v1
kind: Secret
metadata:
  name: game-api-secrets
  namespace: tech-challenge-game
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=TechChallengeGame;Username=postgres;Password=12345"
  Elasticsearch__ApiKey: "RGpvQXRaa0JiMU5kV1RJZTZEQXQ6S3JvcUI3b3FQeHRpblhLckk3TFJQQQ=="
  Serilog__WriteTo__1__Args__apiKey: "RGpvQXRaa0JiMU5kV1RJZTZEQXQ6S3JvcUI3b3FQeHRpblhLckk3TFJQQQ=="